language: python
python:
  - "3.6"
env:
  - DJANGO=2.2
before_install:
  - cd canvas_syllabus_export/requirements
install:
  - "pip install -r test.txt"
script:
  - cd ../..
  - python manage.py test
